#部署为集群时的配置文件
server:
    port: 3000
    tomcat:
        uri-encoding: UTF-8
eureka:
    instance:
        appname: Eureka 注册中心
        prefer-ip-address: true
        lease-renewal-interval-in-seconds: 30
        lease-expiration-duration-in-seconds: 90
    client:
        #是否将自己注册到注册中心上，eureka集群部署时为true
        register-with-eureka: true
        #是否从注册中心上获取注册信息，eureka集群部署时为true
        fetch-registry: true
        service-url:
            #集群部署时通过环境变量设置为其他eureka-server的地址和端口
            defaultZone: http://${EUREKA_SERVER_HOST}:${EUREKA_SERVER_PORT}/eureka

    server:
        #是否开启自我保护模式，一旦进入该模式，Eureka Server就会保护服务注册表中的信息，不再删除服务注册表中的数据
        enable-self-preservation: false
        #清理无效服务的时间间隔
        eviction-interval-timer-in-ms: 10000